import express from 'express';
import cors from 'cors';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import sharp from 'sharp';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ 
    status: 'ok', 
    message: 'Mug Mockup API is running',
    timestamp: new Date().toISOString()
  });
});

// Generate mockup with automatic compression
app.post('/api/generate-mockup', async (req, res) => {
  try {
    const { mockupUrl, designUrl, compress = true, quality = 85 } = req.body;

    // Validate inputs
    if (!mockupUrl || !designUrl) {
      return res.status(400).json({ 
        success: false,
        error: 'Missing required fields: mockupUrl and designUrl' 
      });
    }

    console.log('🎨 Processing mockup request...');
    console.log('📸 Mockup URL:', mockupUrl);
    console.log('🎨 Design URL:', designUrl);

    // Fetch images from URLs
    const mockupResponse = await fetch(mockupUrl);
    if (!mockupResponse.ok) {
      throw new Error(`Failed to fetch mockup image: ${mockupResponse.statusText}`);
    }
    const mockupBuffer = await mockupResponse.arrayBuffer();
    const mockupBase64 = Buffer.from(mockupBuffer).toString('base64');
    const mockupMimeType = mockupResponse.headers.get('content-type') || 'image/png';

    const designResponse = await fetch(designUrl);
    if (!designResponse.ok) {
      throw new Error(`Failed to fetch design image: ${designResponse.statusText}`);
    }
    const designBuffer = await designResponse.arrayBuffer();
    const designBase64 = Buffer.from(designBuffer).toString('base64');
    const designMimeType = designResponse.headers.get('content-type') || 'image/png';

    // Initialize Gemini AI
    const ai = new GoogleGenAI({ 
      apiKey: process.env.GEMINI_API_KEY 
    });

    const model = 'gemini-2.5-flash-image';

    const prompt = `You are a world-class graphic designer specializing in product mockups. 
I am providing two images:
1. A base "Mug Mockup" image (blank mug photo).
2. A "Design" image (artwork/logo to apply).

Your task:
- Intelligently identify the visible surface of the mug in the base mockup.
- Map the "Design" image onto that surface.
- Ensure the design follows the physical curvature of the mug perfectly.
- Match the lighting, shadows, and reflections of the original scene so the design looks naturally printed on the mug, not just floating on top.
- The output should be a single final composite image of the mug with the design applied.
- Retain the original background and surrounding elements of the mockup.

Generate a realistic product mockup image.`;

    console.log('⚡ Calling Gemini API...');

    // Call Gemini API
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: mockupBase64,
              mimeType: mockupMimeType,
            },
          },
          {
            inlineData: {
              data: designBase64,
              mimeType: designMimeType,
            },
          },
          { text: prompt },
        ],
      },
    });

    // Extract result
    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No response from AI model");
    }

    let resultImageBase64 = null;
    let resultMimeType = 'image/png';

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        resultImageBase64 = part.inlineData.data;
        resultMimeType = part.inlineData.mimeType;
        break;
      }
    }

    if (!resultImageBase64) {
      throw new Error("No image in response");
    }

    console.log('✅ Mockup generated by Gemini');

    // 🗜️ COMPRESS OUTPUT (if enabled)
    if (compress) {
      const originalBuffer = Buffer.from(resultImageBase64, 'base64');
      const originalSizeMB = (originalBuffer.length / 1024 / 1024).toFixed(2);
      
      console.log(`📦 Original size: ${originalSizeMB} MB`);
      console.log('🗜️ Compressing for Etsy...');

      // Compress image
      const compressedBuffer = await sharp(originalBuffer)
        .resize(2000, 2000, { 
          fit: 'inside',
          withoutEnlargement: true 
        })
        .jpeg({ 
          quality: quality,  // Default 85
          mozjpeg: true      // Better compression
        })
        .toBuffer();

      const compressedSizeKB = (compressedBuffer.length / 1024).toFixed(2);
      const reduction = ((1 - compressedBuffer.length / originalBuffer.length) * 100).toFixed(0);

      console.log(`✅ Compressed size: ${compressedSizeKB} KB`);
      console.log(`💰 Reduction: ${reduction}%`);

      // Return compressed image
      const compressedBase64 = compressedBuffer.toString('base64');
      
      return res.json({
        success: true,
        image: `data:image/jpeg;base64,${compressedBase64}`,
        mimeType: 'image/jpeg',
        originalSizeMB: originalSizeMB,
        compressedSizeKB: compressedSizeKB,
        reduction: `${reduction}%`,
        timestamp: new Date().toISOString()
      });

    } else {
      // Return original without compression
      console.log('⚠️ Compression disabled, returning original');
      
      return res.json({
        success: true,
        image: `data:${resultMimeType};base64,${resultImageBase64}`,
        mimeType: resultMimeType,
        timestamp: new Date().toISOString()
      });
    }

  } catch (error) {
    console.error('❌ Error generating mockup:', error.message);
    res.status(500).json({ 
      success: false,
      error: 'Failed to generate mockup',
      message: error.message 
    });
  }
});

// Start server
app.listen(PORT, () => {
  console.log('='.repeat(50));
  console.log('🎨 Mug Mockup API Server (with compression)');
  console.log('='.repeat(50));
  console.log(`🚀 Server running on port ${PORT}`);
  console.log(`📍 Health: http://localhost:${PORT}/health`);
  console.log(`📍 API: http://localhost:${PORT}/api/generate-mockup`);
  console.log(`🔑 Gemini API Key: ${process.env.GEMINI_API_KEY ? '✅ Set' : '❌ Missing'}`);
  console.log('='.repeat(50));
});
